spring.application.name=tomato

#Database configuration and connection 
spring.datasource.url=jdbc:mysql://localhost:3306/tomato_db
spring.datasource.username=root
spring.datasource.password=#Students@69
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate commands 
spring.jpa.show-sql=true  
spring.jpa.hibernate.ddl-auto=update
